# Generated by Django 3.2.10 on 2021-12-09 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('start_year', models.IntegerField()),
                ('finish_year', models.IntegerField()),
                ('info', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='artist.artist')),
            ],
        ),
    ]
