# Generated by Django 3.2.10 on 2021-12-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='year',
        ),
    ]
