# Generated by Django 3.2.10 on 2021-12-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_remove_work_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='finish_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
