# Generated by Django 3.2.10 on 2021-12-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20211210_0854'),
        ('work', '0003_auto_20211210_1307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('artist', 'name')},
        ),
    ]
