# Generated by Django 3.2.10 on 2021-12-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_work_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
