# Generated by Django 3.2.10 on 2021-12-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('born', models.IntegerField()),
                ('died', models.IntegerField()),
                ('period', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
