# Generated by Django 3.2.10 on 2021-12-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20211210_0553'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together={('last_name', 'first_name', 'region')},
        ),
    ]
