# Generated by Django 3.2.10 on 2021-12-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_artist_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='region',
            new_name='nationality',
        ),
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together={('last_name', 'first_name', 'nationality')},
        ),
    ]
