# Generated by Django 3.2.10 on 2021-12-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20211210_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='born',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='died',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profession',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
