# Generated by Django 3.2.10 on 2021-12-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_auto_20211213_2358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together={('last_name', 'nationality', 'died', 'period', 'profession')},
        ),
    ]
